steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/wiscro/wiscro-server:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wiscro/wiscro-server:latest']

images:
- 'gcr.io/wiscro/wiscro-server:latest'

