steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/wiscro/express-app:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wiscro/express-app:latest']

images:
- 'gcr.io/wiscro/express-app:latest'